<a href="https://colab.research.google.com/github/me-sajal/broadway-learning-mlclass/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to numpy
* Numpy is scientific computing library 
* Used to creare n-dimensional array


In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
%%bash
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Import Numpy


In [ ]:
import numpy as np


# Check Verson of Numpy


In [ ]:
np.__version__


'1.22.4'

# Creating an array in numpy
`np.array()`

In [ ]:
x = np.array([])

In [ ]:
x #default datatype float 64


array([], dtype=float64)

In [ ]:
type(x) # ndarray : n-dimensional array 

numpy.ndarray

# Creating an array

In [ ]:
x = np.array([1, 2, 5, 10, 20, 25, 50, 100, 500, 1000])

In [ ]:
x


array([   1,    2,    5,   10,   20,   25,   50,  100,  500, 1000])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim # Computes the dimension of array

1

In [ ]:
len(x)

10

In [ ]:
x.shape # Shape of array

(10,)

# Indexing and slicing in array

In [ ]:
x = np.array([1, 2, 5, 10, 20, 25, 50, 100, 500, 1000])

In [ ]:
x[4]

20

In [ ]:
x[1]

2

In [ ]:
x[-1]

1000

In [ ]:
x[9]

1000

In [ ]:
x[4:7] #Slicing to get 20 25 50

array([20, 25, 50])

In [ ]:
x[-2:] #last two elements

array([ 500, 1000])

In [ ]:
x[:3] #first 3 elements

array([1, 2, 5])

# Diffrences between python list and numpy array
* Numpy array are memory efficient than python list
* Nympy array are faster than python list
* Numpy array supports homogenous data type but python supports multiple data types.


In [ ]:
np.random.randint(1,10) #generates random integer on range [1, 10] where 10 doesnot exits


3

In [ ]:
# If we want generate same random number then np.random.seed(seed_value)
np.random.seed(55)
np.random.randint(1,10)

8

In [ ]:
x = np.array([2, 10, 20, 50, 100], dtype = np.int8) #control dtype datatype and memory
x

array([  2,  10,  20,  50, 100], dtype=int8)

In [ ]:
x = np.array([2, 10, 20, 50, 100], dtype = np.int16) # we can control datatype -> memory efficient
x

array([  2,  10,  20,  50, 100], dtype=int16)

In [ ]:
np.random.seed(40)
list1 =[np.random.randint(1,10) for i in range (50000)]
print(list1)

[7, 8, 6, 9, 9, 3, 2, 8, 3, 4, 8, 4, 1, 2, 6, 9, 5, 5, 9, 7, 4, 4, 8, 8, 2, 4, 6, 3, 3, 4, 8, 4, 3, 3, 6, 1, 2, 8, 4, 9, 6, 4, 3, 7, 4, 6, 5, 6, 6, 9, 1, 2, 2, 5, 9, 3, 6, 8, 9, 7, 5, 3, 8, 4, 1, 6, 6, 6, 1, 4, 3, 5, 8, 7, 8, 8, 4, 5, 5, 8, 3, 1, 9, 4, 9, 6, 6, 6, 8, 6, 5, 1, 4, 5, 7, 3, 6, 4, 8, 4, 3, 7, 3, 8, 9, 2, 8, 8, 3, 1, 1, 6, 1, 7, 1, 4, 2, 4, 5, 9, 2, 2, 5, 9, 7, 1, 9, 1, 1, 8, 7, 9, 5, 1, 3, 1, 2, 5, 4, 3, 2, 4, 6, 5, 5, 2, 7, 6, 2, 9, 8, 8, 7, 5, 8, 2, 7, 5, 5, 7, 2, 9, 2, 6, 7, 1, 4, 1, 5, 5, 9, 4, 3, 2, 1, 9, 5, 9, 9, 2, 7, 1, 2, 6, 6, 2, 9, 5, 1, 2, 7, 9, 1, 4, 8, 1, 1, 1, 9, 2, 8, 2, 6, 9, 9, 8, 5, 3, 2, 5, 9, 4, 2, 4, 8, 4, 3, 3, 8, 4, 8, 5, 2, 6, 1, 6, 2, 7, 2, 1, 8, 9, 1, 2, 6, 6, 4, 6, 3, 2, 6, 7, 5, 7, 2, 1, 1, 9, 1, 7, 9, 8, 8, 5, 4, 9, 6, 8, 3, 4, 1, 8, 5, 9, 6, 5, 7, 8, 8, 6, 6, 7, 8, 9, 1, 6, 1, 3, 5, 9, 4, 6, 6, 2, 2, 4, 1, 2, 7, 3, 5, 7, 5, 5, 5, 7, 8, 5, 7, 6, 6, 7, 6, 8, 7, 2, 5, 3, 7, 8, 5, 9, 9, 6, 2, 9, 8, 4, 9, 3, 6, 3, 3, 2, 2, 6, 3, 2, 4, 7, 6, 9, 1, 

In [ ]:
%%time
sq = [item **2 for item in list1] #slower than array

CPU times: user 14.4 ms, sys: 0 ns, total: 14.4 ms
Wall time: 15.5 ms


In [ ]:
list1_array = np.array(list1) # faster than compreension

In [ ]:
%%time
sq = list1_array ** 2

CPU times: user 1.3 ms, sys: 24 µs, total: 1.32 ms
Wall time: 1.33 ms



 Homogeneous datatype in numpy array 


In [ ]:
bucket = ['apple', 'Purse', 20, 22.5, True]

In [ ]:
type(bucket[-1])

bool

In [ ]:
bucket_array = np.array(bucket)

In [ ]:
bucket_array  # All itemes are in string -> Homogenous dataype

array(['apple', 'Purse', '20', '22.5', 'True'], dtype='<U32')

In [ ]:
type(bucket_array[-1])

numpy.str_

In [ ]:
gift = ['paisa','Gadi','Ghadi','Books']
gift.append('Rose')
gift

['paisa', 'Gadi', 'Ghadi', 'Books', 'Rose']

In [ ]:
gift_array = np.array(gift)
# gift_array.append('rose') donot append like list in numpy use np.append() instead
np.append(gift_array,"jutta")

array(['paisa', 'Gadi', 'Ghadi', 'Books', 'Rose', 'jutta'], dtype='<U5')

# np.arrange() in equlivalent to range () in python

In [ ]:
list (range(1,10,2))

[1, 3, 5, 7, 9]

In [ ]:
np.arange(1,10,2)


array([1, 3, 5, 7, 9])

# Generate numbers using numpy


In [ ]:
np.zeros(5, dtype = np.int8)

array([0, 0, 0, 0, 0], dtype=int8)

In [ ]:
np.zeros(6, dtype = np.float16)

array([0., 0., 0., 0., 0., 0.], dtype=float16)

In [ ]:
np.ones(5, dtype = np.int8)

array([1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [ ]:
np.empty(8)

array([2.84560626e-316, 0.00000000e+000, 2.44141287e-152, 2.35570319e+251,
       9.30277090e+242, 5.37625007e+241, 1.48973020e+214, 8.66587581e-316])

Zeros and ons are usied in binary image masking in computer vision.